services:
  analysis-env:
    image:  meirikson/cdc_diabetes_prediction:eb1109b
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/diabetes_prediction
    deploy:
      resources:
        limits:
          memory: 10G
    platform: linux/amd64