name: cdc_diabetes_prediction
channels:
  - conda-forge
dependencies:
  - ipykernel=6.26.0
  - vegafusion-jupyter=1.4.3
  - scikit-learn=1.3.2
  - altair=5.1.2
  - jupyter_contrib_nbextensions=0.7.0
  - vegafusion-python-embed=1.4.3
  - matplotlib=3.10.8
  - jupyterlab=4.5.0
  - ucimlrepo=0.0.7
  - vegafusion=1.4.3
  - notebook=6.5.4
  - python=3.11.6
  - vl-convert-python=1.0.1
  - pandas=2.1.2
  - pandera=0.27.0
  - click=8.3.1
  - quarto=1.8.26
  - conda-lock=3.0.4
  - tabulate=0.9.0
  - requests=2.31.0
  - pytz=2025.2
  - jsonschema=4.25.0
  - toolz=1.0.0
  - pytest=8.4.1
  - make=4.2.1
  - pip=25.3
    # - deepchecks==0.18.1
