name: vancouver_tree_predictions
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.3.3
  - python=3.12.12
  - jupyterlab=4.5.0
  - scikit-learn=1.7.2
  - numpy=2.3.5
  - ucimlrepo=0.0.7
