name: cdc_diabetes_prediction
channels:
  - conda-forge
dependencies:
  - jupyter_contrib_nbextensions=0.7.0
  - altair=5.1.2
  - python=3.11.6
  - jupyterlab=4.5.0
  - requests=2.31.0
  - notebook=6.5.4
  - ipykernel=6.26.0
  - vegafusion-python-embed=1.4.3
  - vegafusion=1.4.3
  - pandas=2.1.2
  - ucimlrepo=0.0.7
  - vl-convert-python=1.0.1
  - scikit-learn=1.3.2
  - vegafusion-jupyter=1.4.3
  - conda-lock=3.0.4
